package com.example.pizzaapp.enums;

/**
 */
public enum Toppings {
    CHICKEN, PEPPERONI, SAUSAGE, BEEF,
    GROUNDBEEF, HAM, SHRIMP, SQUID, MUSHROOM,
    CRABMEAT, BLACKOLIVE, CORN,
    MOZZARELLA, ONION, TOMATOES,
    CHEDDAR, JALAPENOS, AVOCADO, CILANTRO,
    GREENPEPPER, BASIL, PINEAPPLE;
}
